export type CategoryData = {
    "id": string,
    "title": string,
    "category": string,
    "price": number,
}

export const defaultData: Record<string, CategoryData[]> = {
    'Rare Tests': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'lipid metabolism': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'kidney function test': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'heart & muscle': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'thyroid': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'paternity': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Pharmacology/Toxicology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Cerology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'CSF': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Iron Studies': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Coagulation': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'TB Department': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Citology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Glucose Metabolism': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Liver/Pancreas/Git': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Immunology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Tumor Markers': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'General Endocrine': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Pregnancy': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'HIV Tests': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Andrology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Alergy': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Haematology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Nutrition': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Molecular Biology (PCR)': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Microbiology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
    'Histology': [
        { id: '1', title: 'Cholesterol', category: 'lipid metabolism', price: 3300 },
        { id: '2', title: 'LDL (Measured)', category: 'lipid metabolism', price: 4200 },
        { id: '3', title: 'HDL Cholesterol', category: 'lipid metabolism', price: 4800 },
        { id: '4', title: 'Lipogram (CHOL/HDL/TRIG/LDL)', category: 'lipid metabolism', price: 8200 },
        { id: '5', title: 'Triglycerides', category: 'lipid metabolism', price: 3000 },
    ],
}